website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from .models import User,Locaciones,Cargo
from . import db

views = Blueprint('views', __name__)

@views.route("/", methods=['GET', 'POST'])
@login_required
def home():
    if request.method == "POST":
        nombre = request.form.get('Nombre')
        apellido = request.form.get('Apellido')
        localizacionID = request.form.get('localID')
        cargoID = request.form.get('Cargo')
        estado = request.form.get('Estado')
        localidad = Locaciones.query.filter_by(id=localizacionID).first()
        cargos = Cargo.query.filter_by(id=cargoID).first()
        if localidad:
            if cargos:
                if estado == 'on':
                    estadito = True
                else:
                    estadito = None
                print(current_user.id)
                local= User.query.get(current_user.id)
                local.nombre = nombre
                local.apellido = apellido
                local.localizacionID = localizacionID
                local.cargoID = cargoID
                local.estado = estadito
                db.session.commit()
                flash('Actualizado con exito', category='success')
            else:
                flash('El cargo no existe', category='error') 
        else:
            flash('La localidad no existe', category='error')

    return render_template("home.html", user=current_user)

###########################
# Metodos de Localizacion #
###########################

@views.route('/deletelocate/<id>')
def deleteLocate(id):
    registro = Locaciones.query.get(id)
    db.session.delete(registro)
    db.session.commit()
        
    return redirect(url_for("views.localizaciones"))

@views.route('/updateLocate/<id>', methods=['GET', 'POST'])
def updateLocate(id):
    if request.method == "POST":
        localizacion = request.form.get('local')
        Local = Locaciones.query.filter_by(localizacion=localizacion).first()
        if len(localizacion) < 1:
            flash('Debe tener un nombre la locacion!', category='error')
        elif Local:
            porsi = Locaciones.query.filter_by(id=id).first()
            if porsi:
                estado = request.form.get('Estado')
                if estado == 'on':
                    estadito = True
                else:
                    estadito = None
                local= Locaciones.query.get(id)
                local.localizacion = localizacion
                local.estado = estadito
                db.session.commit() 
            else:
                flash('La localizacion ya existe', category='error')
        else:
            estado = request.form.get('Estado')
            if estado == 'on':
                estadito = True
            else:
                estadito = None
            local= Locaciones.query.get(id)
            local.localizacion = localizacion
            local.estado = estadito
            db.session.commit()

        return redirect(url_for("views.localizaciones"))

    locaciones = Locaciones.query.get(id)

    return render_template("updateLocate.html", user=current_user, locaciones=locaciones)

@views.route('/localizaciones', methods=['GET', 'POST'])
def localizaciones():
    Localizaciones = Locaciones.query.all()

    if request.method == 'POST':

        localizacion = request.form.get('local')
        Local = Locaciones.query.filter_by(localizacion=localizacion).first()

        if len(localizacion) < 1:
            flash('Debe tener un nombre la locacion!', category='error')
        elif Local:
            flash('La localizacion ya existe', category='error')
        else:
            new_note = Locaciones(localizacion=localizacion)
            db.session.add(new_note)
            db.session.commit()
            return redirect(url_for("views.localizaciones"))
            flash('Locacion añadida!', category='success')

    return render_template("localizaciones.html", user=current_user, Localizaciones=Localizaciones)

#####################
# Metodos de Cargos #
#####################
    
@views.route('/deleteCargos/<id>')
def deleteCargos(id):
    registro = Cargo.query.get(id)
    db.session.delete(registro)
    db.session.commit()
        
    return redirect(url_for("views.cargos"))

@views.route('/updateCargos/<id>', methods=['GET', 'POST'])
def updateCargos(id):
    if request.method == "POST":
        cargo = request.form.get('local')
        Local = Cargo.query.filter_by(cargo=cargo).first()
        if len(cargo) < 1:
            flash('Debe tener un nombre el cargos!', category='error')
        elif Local:
            porsi = Cargo.query.filter_by(id=id).first()
            if porsi:
                estado = request.form.get('Estado')
                if estado == 'on':
                    estadito = True
                else:
                    estadito = None
                local= Cargo.query.get(id)
                local.cargo = Cargos
                local.estado = estadito
                db.session.commit() 
            else:
                flash('El cargo ya existe', category='error')
        else:
            estado = request.form.get('Estado')
            if estado == 'on':
                estadito = True
            else:
                estadito = None
            local= Cargo.query.get(id)
            local.cargo = Cargos
            local.estado = estadito
            db.session.commit()

        return redirect(url_for("views.cargos"))

    cargos= Cargo.query.get(id)

    return render_template("updateCargos.html", user=current_user, cargos=cargos)

@views.route('/cargos', methods=['GET', 'POST'])
def cargos():
    cargo = Cargo.query.all()

    if request.method == 'POST':

        cargos = request.form.get('cargo')
        Local = Cargo.query.filter_by(cargo=cargos).first()

        if len(cargos) < 1:
            flash('Debe tener un nombre el cargo!', category='error')
        elif Local:
            flash('El cargo ya existe', category='error')
        else:
            new_note = Cargo(cargo=cargos)
            db.session.add(new_note)
            db.session.commit()
            flash('Cargo añadida!', category='success')
            return redirect(url_for("views.cargos"))

    return render_template("cargos.html", user=current_user, cargo=cargo)

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" ,initial-scale="1" />
    <!-- Boostrap -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />
    <!-- Fuente Awesome -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.0/css/fontawesome.min.css"
      integrity="sha384-z4tVnCr80ZcL0iufVdGQSUzNvJsKjEtqYZjiQrrYKlpGow+btDHDfQWkFjoaz/Zr"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="../static/estilos.css">
    <title>{% block title %}Home{% endblock%}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="localizaciones" href="/localizaciones">Localizaciones</a>
          <a class="nav-item nav-link" id="cargos" href="/cargos">Cargos</a>
          <form class="form-inline my-2 my-lg-0">
          <a class="my-2 my-lg-0 nav-item nav-link" id="signUp" href="/logout">Logout</a>
        </form>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} 
  {% if  messages %} 
  {% for category, message in messages %} 
  {% if category ==  'error' %}
  <div class="alert alert-danger alter-dismissable fade show" role="alert">
    {{ message }}
    <button type="button" class="close"  data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% else %}
  <div class="alert alert-success alter-dismissable fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>

    <!-- JavaScript Boostrap-->
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.14.6/dist/umd/popper.min.js"
      integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.min.js"
      integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

website/templates/cargos.html
{% extends "base.html" %} {% block title %}Localizaciones{% endblock %} {% block
  content %}
  <div data-content id="Cargos">
    <form method="POST">
      <h3 align="center">Cargos</h3>
      <div class="container text-center">
        <div class="row">
          <div class="col">
            <div class="form-group">
              <div class="form-group">
                <label class = "local_inicial"for="cargo">Agregar otro cargo</label>
                <input
                  type="text"
                  class="form-control"
                  id="cargo"
                  name="cargo"
                  placeholder="Ingresar Cargo"
                />
              </div>
            </div>
          </div>
          <div class="col col-lg-2">
            <button type="submit" class="btn btn-primary boton">Crear</button>
          </div>
        </div>
      </div>
      <br />
      <br />
  
      <table class="table table-responsive table-hover">  
        <thead>
          <tr>
            <th>localizacion ID</th>
            <th>Nombre localizacion</th>
            <th>Estado Actual</th>
            <th>Actualizar</th>
            <th>Borrar</th>
          </tr>
        </thead>
        {% for cargo in cargo %} 
          <tr>
            <td>{{cargo.id}}</td>
            <td>{{cargo.cargo}}</td>
            <td>{{cargo.estado}}</td>
            <td>
              <a
                type="button"
                class="btn btn-primary"
                href="{{url_for('views.updateCargos', id=cargo.id)}}"
                >Actualizar</a
              >
            </td>
            <td>
              <a
                type="button"
                class="btn btn-primary"
                href="{{url_for('views.deleteCargos', id=cargo.id)}}"
                >Borrar</a
              >
            </td>
          </tr>
          {% endfor %}
      </table>
    </form>
  </div>
  {% endblock %}

website/templates/home.html
{% extends "base.html" %} {% block title %}Change{% endblock %} {% block content
%}

<div class="content">
  <div data-content id="Usuario">
    <form method="POST">
      <h3 align="center">Usuario</h3>
      <div class="form-group">
        <label class = "local_inicial1" for="Nombre">Nombre</label>
        <input
          type="text"
          class="form-control"
          id="Nombre"
          name="Nombre"
          value="{{user.nombre}}"
        />
      </div>
      <div class="form-group">
        <label class = "local_inicial1" for="Apellido">Apellido</label>
        <input
          type="text"
          class="form-control"
          id="Apellido"
          name="Apellido"
          value="{{user.apellido}}"
        />
      </div>
      <div class="form-group">
        <label class = "local_inicial1" for="localID">localizacion ID</label>
        <input
          type="number"
          class="form-control"
          id="localID"
          name="localID"
          value="{{user.localizacionID}}"
        />
      </div>
      <div class="form-group">
        <label class = "local_inicial1" for="CargoID">Cargo ID</label>
        <input
          type="number"
          class="form-control"
          id="Cargo"
          name="Cargo"
          value="{{user.cargoID}}"
        />
      </div>
      <label class = "local_inicial1" for="Estado">Estado Actual {{user.estado}}</label>
      <div class="form-check">
        <div class="form-check">
          <input
            class="form-check-input Usuario_pug"
            value="on"
            type="checkbox"
            id="Estado"
            name="Estado"
            checked
          />
        </div>
      </div>

      <br />
      <br />
      <div class="col text-center">
        <button type="submit" class="btn btn-primary">Actualizar</button>
      </div>
    </form>
  </div>

{% endblock %}

website/templates/localizaciones.html
{% extends "base.html" %} {% block title %}Localizaciones{% endblock %} {% block
content %}
<div data-content id="Locaciones">
  <form method="POST">
    <h3 align="center">Localizaciones</h3>
    <div class="container text-center">
      <div class="row">
        <div class="col">
          <div class="form-group">
            <div class="form-group">
              <label class = "local_inicial"for="local">Agregar Otra Localizacion</label>
              <input
                type="text"
                class="form-control"
                id="local"
                name="local"
                placeholder="Ingresar Locacion"
              />
            </div>
          </div>
        </div>
        <div class="col col-lg-2">
          <button type="submit" class="btn btn-primary boton">Crear</button>
        </div>
      </div>
    </div>
    <br />
    <br />

    <table class="table table-responsive table-hover">  
      <thead>
        <tr>
          <th>localizacion ID</th>
          <th>Nombre localizacion</th>
          <th>Estado Actual</th>
          <th>Actualizar</th>
          <th>Borrar</th>
        </tr>
      </thead>
      {% for Locaciones in Localizaciones %} 
        <tr>
          <td>{{Locaciones.id}}</td>
          <td>{{Locaciones.localizacion}}</td>
          <td>{{Locaciones.estado}}</td>
          <td>
            <a
              type="button"
              class="btn btn-primary"
              href="{{url_for('views.updateLocate', id=Locaciones.id)}}"
              >Actualizar</a
            >
          </td>
          <td>
            <a
              type="button"
              class="btn btn-primary"
              href="{{url_for('views.deleteLocate', id=Locaciones.id)}}"
              >Borrar</a
            >
          </td>
        </tr>
        {% endfor %}
    </table>
  </form>
</div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
      <label for="email">identificacion</label>
      <input
        type="number"
        class="form-control"
        id="identificacion"
        name="identificacion"
        placeholder="Ingresa identificacion"
      />
    </div>
    <div class="form-group">
      <label for="password">Contraseña</label>
      <input
        type="password"
        class="form-control"
        id="password"
        name="password"
        placeholder="Ingresa Contraseña"
      />
    <br />
    <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Registro{% endblock %} {% block
  content %}
  <form method="POST">
    <h3 align="center">Registro</h3>
    <div class="form-group">
      <label for="Nombre">Nombre</label>
      <input
        type="text"
        class="form-control"
        id="Nombre"
        name="Nombre"
        placeholder="Ingresa Nombre"
      />
    </div>
    <div class="form-group">
      <label for="Apellido">Apellido</label>
      <input
        type="text"
        class="form-control"
        id="Apellido"
        name="Apellido"
        placeholder="Ingresa Apellido"
      />
    </div>
    <div class="form-group">
      <label for="identificacion">identificacion</label>
      <input
        type="number"
        class="form-control"
        id="identificacion"
        name="identificacion"
        placeholder="Ingresa identificacion"
      />
    </div>
    <div class="form-group">
      <label for="password1">Contraseña</label>
      <input
        type="password"
        class="form-control"
        id="password1"
        name="password1"
        placeholder="Ingresa Contraseña"
      />
    </div>
    <div class="form-group">
      <label for="password2">Contraseña (Confirmacion)</label>
      <input
        type="password"
        class="form-control"
        id="password2"
        name="password2"
        placeholder="Confirma Contraseña"
      />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
  {% endblock %}

website/templates/updateCargos.html
{% extends "base.html" %} {% block title %}Change{% endblock %} {% block content
    %}
    <form method="POST">
    <br />
    <br />
    <h3 align="center">Actualizacion Cargos</h3>
    <br />
    <br />
    <div class="container text-center">
      <table class="table table-responsive table-hover">  
        <thead>
          <tr>
            <th>Nombre localizacion</th>
            <th>Estado Actual</th>
            <th>Actualizar</th>
            <th>Borrar</th>
          </tr>
        </thead>
          <tr>
            <td><input
                type="text"
                class="form-control"
                id="local"
                name="local"
                value="{{cargos.cargo}}"
              /></td>
            <td><input
                  class="form-check-input"
                  value="on"
                  type="checkbox"
                  id="Estado"
                  name="Estado"
                  checked
                /></td>
            <td>
              <button type="submit" class="btn btn-primary">Submit</button>
            </td>
          </tr>
      </table>
    </div>
    </form>
    {% endblock %}
    

website/templates/updateLocate.html
{% extends "base.html" %} {% block title %}Change{% endblock %} {% block content
%}
<form method="POST">
  <br />
  <br />
  <h3 align="center">Actualizacion Locaciones</h3>
  <br />
  <br />
  <div class="container text-center">
    <table class="table table-responsive table-hover">
      <thead>
        <tr>
          <th>Nombre localizacion</th>
          <th>Estado Actual</th>
          <th>Actualizar</th>
        </tr>
      </thead>
      <tr>
        <td>
          <input
            type="text"
            class="form-control"
            id="local"
            name="local"
            value="{{locaciones.localizacion}}"
          />
        </td>
        <td>
          <input
            class="form-check-input"
            value="on"
            type="checkbox"
            id="Estado"
            name="Estado"
            checked
          />
        </td>
        <td>
          <button type="submit" class="btn btn-primary">Submit</button>
        </td>
      </tr>
    </table>
  </div>
</form>
{% endblock %}